const fetch = require('node-fetch');

const API = 'https://api.github.com';

function authHeaders() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error('GITHUB_TOKEN is not set');
  return {
    Authorization: `Bearer ${token}`,
    Accept: 'application/vnd.github+json',
    'Content-Type': 'application/json',
    'X-GitHub-Api-Version': '2022-11-28'
  };
}

async function createRepo(slug) {
  const owner = process.env.GITHUB_OWNER;
  if (!owner) throw new Error('GITHUB_OWNER is not set');

  const res = await fetch(`${API}/user/repos`, {
    method: 'POST',
    headers: authHeaders(),
    body: JSON.stringify({
      name: slug,
      description: 'Generated by Cymor Website Builder',
      private: false,
      auto_init: false
    })
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`GitHub repo creation failed (${res.status}): ${err}`);
  }

  const data = await res.json();
  return { repoUrl: data.html_url, fullName: data.full_name };
}

/** Creates a single file in the repo via the Contents API (base64-encoded body) */
async function putFile(fullName, filePath, content, message) {
  const res = await fetch(`${API}/repos/${fullName}/contents/${filePath}`, {
    method: 'PUT',
    headers: authHeaders(),
    body: JSON.stringify({
      message,
      content: Buffer.from(content, 'utf-8').toString('base64')
    })
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`GitHub commit failed for ${filePath} (${res.status}): ${err}`);
  }

  return res.json();
}

/** Commits index.html + robots.txt + sitemap.xml as one repo's initial content */
async function commitSite(slug, files) {
  const { repoUrl, fullName } = await createRepo(slug);

  for (const [filePath, content] of Object.entries(files)) {
    await putFile(fullName, filePath, content, `Add ${filePath}`);
  }

  return { repoUrl, fullName };
}

module.exports = { commitSite };
