const archiver = require('archiver');

/**
 * Streams a ZIP of the generated site straight to the HTTP response —
 * nothing is written to disk, so there's no cleanup and no Render
 * ephemeral-filesystem issue to worry about.
 */
function streamProjectZip(res, slug, files) {
  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="${slug}.zip"`);

  const archive = archiver('zip', { zlib: { level: 9 } });
  archive.on('error', (err) => {
    throw err;
  });

  archive.pipe(res);

  for (const [filePath, content] of Object.entries(files)) {
    archive.append(content, { name: filePath });
  }

  // A minimal README inside the ZIP so the export is usable standalone
  archive.append(
    `# ${slug}\n\nGenerated by Cymor Website Builder.\n\nTo use:\n1. Open index.html directly in a browser, or\n2. Deploy the folder to any static host (Vercel, Netlify, GitHub Pages).\n`,
    { name: 'README.md' }
  );

  archive.finalize();
}

module.exports = { streamProjectZip };
